name: autobooter test
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pre-req
        run: pip install pyserial pyinstaller
      - name: pyinstaller
        run: pyinstaller -F autobooter.py
      - name: looksies
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/autobooter.exe
